- name: Install Mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy the mongodb repo
    ansible.builtin.copy:
      src: /home/centos/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB packages
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

