- name: Install Mongodb component
  hosts: mongodb
  becom: yes
  tasks:
  - name: Copy the mongodb repo
    ansible.builtin.copy:
    src: /home/centos/mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB packages
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: Enable and start MongoDB service
    service:
      name: mongod
      state: started
      enabled: yes
